project_id = "uoxcnkqjxthivsvxqonj"

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.import-users]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false
