project_id = "uoxcnkqjxthivsvxqonj"

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.import-users]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.admin-recovery]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.get-users-with-emails]
verify_jwt = false

[functions.create-professor]
verify_jwt = false

[functions.analisar-observacoes]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.sync-alunos-externos]
verify_jwt = false

[functions.delete-users-bulk]
verify_jwt = false

[functions.delete-alunos-por-segmento]
verify_jwt = false

[functions.sync-alunos-pull]
verify_jwt = false

[functions.import-alunos-rapido]
verify_jwt = false

[functions.gerar-contas-alunos]
verify_jwt = false

[functions.receber-sugestao-n8n]
verify_jwt = false

[functions.reset-aluno-dados]
verify_jwt = false
